# HTTP Server
[server]
    Address          = ":7777"
    ServerRoot       = ""
    ServerAgent      = ""
    IndexFiles       = []
    AccessLogEnabled = true
    ErrorLogEnabled  = true
    PProfEnabled     = false
    LogPath          = "./log/goframe-vue-admin/server"
    SessionIdName    = ""
    SessionPath      = ""
    SessionMaxAge    = ""
    DumpRouterMap    = true

# Logger.
[logger]
    Path        = "./log/goframe-vue-admin/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:gdkid,,..@tcp(127.0.0.1:3306)/gf-server"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "../log/goframe-vue-admin/sql"
        Level  = "all"
        Stdout = true